### ISSUE TITLE
Catch2 v3 is not available on older distributions (Debian 12, Ubuntu 22.04)

### ISSUE THREAD

**Issue by krasin** [hirak99/keyshift#2]
I am not sure if any action needs to be taken about this, but reporting the observed behavior:

```
user@desktop12:~/src/github.com/hirak99/keyshift$ ./build.sh
...
CMake Error at CMakeLists.txt:17 (find_package):
  Could not find a configuration file for package "Catch2" that is compatible
  with requested version "3".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/Catch2/Catch2Config.cmake, version: 2.13.10
    /lib/cmake/Catch2/Catch2Config.cmake, version: 2.13.10
```

The problem is that Debian 12 (and Ubuntu 22.04) carry pre-v3 versions of Catch2. On Ubuntu 24.04 the current state is interesting:
https://answers.launchpad.net/ubuntu/noble/+package/catch2

```
catch2 2.13.10-1 in amd64 (Release)
catch2 3.4.0-1build1 in amd64 (Proposed)
catch2 3.4.0-1build1 in amd64 (Release)
catch2 2.13.10-1 in arm64 (Release)
catch2 3.4.0-1build1 in arm64 (Proposed)
catch2 3.4.0-1build1 in arm64 (Release)
catch2 2.13.10-1 in armhf (Release) 
```

It's a mix of 2.13 and 3.4, but it's clear that 3.4 is taking over right now.

Debian Testing (and to the extent, the upcoming Debian 13) has 3.7: https://packages.debian.org/testing/catch2.

So, probably, nothing needs to be done and I will just build catch2 from sources on my machine.

**Comment by hirak99** [comment]
Thanks!

Yes then it makes sense to keep Catch 3.

However, the tests can be optional.

Let me reconfigure CMakeLists.txt to make it optional, and remove the target from the general build instructions.

**Comment by krasin** [comment]
That's a good thought.

**Comment by hirak99** [comment]
`build_minimal.sh` now only builds the main binary, does not depend on catch2. Updated README with this as well.
